UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/4/4a/Oppenheimer_%28film%29.jpg' WHERE titulo = 'Oppenheimer';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Breaking_Bad_logo.svg/500px-Breaking_Bad_logo.svg.png' WHERE titulo = 'Breaking Bad';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/db/Spirited_Away_Japanese_poster.png' WHERE titulo = 'A Viagem de Chihiro';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg' WHERE titulo = 'Interestelar';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg' WHERE titulo = 'Batman: O Cavaleiro das Trevas';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png' WHERE titulo = 'Parasita';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/10/CidadedeDeus.jpg' WHERE titulo = 'Cidade de Deus';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/commons/3/38/Stranger_Things_logo.png' WHERE titulo = 'Stranger Things';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/commons/b/b7/The_Office_Cast.jpg' WHERE titulo = 'The Office';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/d8/Game_of_Thrones_title_card.jpg' WHERE titulo = 'Game of Thrones';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg' WHERE titulo = 'Pulp Fiction: Tempo de Violência';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg' WHERE titulo = 'O Poderoso Chefão';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/commons/3/33/Three_members_of_the_cast_of_Friends.jpg' WHERE titulo = 'Friends';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png' WHERE titulo = 'Matrix';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg' WHERE titulo = 'Toy Story';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/a/ab/La_La_Land_%28film%29.png' WHERE titulo = 'La La Land: Cantando Estações';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg' WHERE titulo = 'Coringa';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg' WHERE titulo = 'A Origem';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Squid_Game_2021_vector_logo_english.svg/500px-Squid_Game_2021_vector_logo_english.svg.png' WHERE titulo = 'Round 6';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/f/fb/Lord_Rings_Fellowship_Ring.jpg' WHERE titulo = 'O Senhor dos Anéis: A Sociedade do Anel';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/a/a3/Get_Out_poster.png' WHERE titulo = 'Corra!';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/18/Titanic_%281997_film%29_poster.png' WHERE titulo = 'Titanic';
UPDATE titulo SET poster_url = 'https://upload.wikimedia.org/wikipedia/en/1/1d/The_Shining_%281980%29_U.K._release_poster_-_The_tide_of_terror_that_swept_America_IS_HERE.jpg' WHERE titulo = 'O Iluminado';
